let subjects = [
    {
        id: '001',
        Subject: 'Maths',
        Location: 'London',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '002',
        Subject: 'Maths',
        Location: 'Oxford',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '003',
        Subject: 'English',
        Location: 'London',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '004',
        Subject: 'English',
        Location: 'York',
        Price: '£80',
        Spaces: 5,
    },
    {
        id: '005',
        Subject: 'Music',
        Location: 'Bristol',
        Price: '£90',
        Spaces: 5,
    },
    {
        id: '006',
        Subject: 'Maths',
        Location: 'London',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '007',
        Subject: 'Maths',
        Location: 'Oxford',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '008',
        Subject: 'English',
        Location: 'London',
        Price: '£100',
        Spaces: 5,
    },
    {
        id: '009',
        Subject: 'English',
        Location: 'York',
        Price: '£80',
        Spaces: 5,
    },
    {
        id: '010',
        Subject: 'Music',
        Location: 'Bristol',
        Price: '£90',
        Spaces: 5,
    },
]
